version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - AUTH=no
      - USER=
      - PASS=

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  adminer:
    image: dockette/adminer:full-php5
    restart: always
    ports:
      - 8082:80
    depends_on:
      - postgres
      - mongo

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=123

  redisadmin:
    image: sasanrose/phpredmin
    restart: always
    ports:
      - 8081:80
    depends_on:
      - redis
    environment:
      - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
      - PHPREDMIN_DATABASE_REDIS_0_PASSWORD=123