export const SEARCH = 'SEARCH';
export const SELECT_USER = 'SELECT_USER';
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS';
export const ADD_USER_PERMISSION = 'ADD_USER_PERMISSION';
export const REMOVE_USER_PERMISSION = 'REMOVE_USER_PERMISSION';
export const UPDATE_USER_TOKEN = 'UPDATE_USER_TOKEN';
export const CLEAR = 'CLEAR';
